### ISSUE TITLE
Instalação e configuração do Plugin do Maven no Eclipse

### ISSUE THREAD

**Issue by gabs-rocha** [TatiTheFreaK/UnimepEngSw01#10]

**Comment by HugoPeressin** [comment]
Imagens do passo a passo foram capturadas.

**Comment by gabs-rocha** [comment]
Já fiz a descrição das imagens

**Comment by gabs-rocha** [comment]
Subi as imagens na wiki, preciso colocar as instruções, mas acabei deixando o arquivo em casa. Porém a estrutura está pronta

**Comment by gabs-rocha** [comment]
Textos colocados e tópico finalizado!!

**Comment by HugoPeressin** [comment]
Revisado.
