### ISSUE TITLE
Escrever os requisitos não funcionais

### ISSUE THREAD

**Issue by HugoPeressin** [TatiTheFreaK/UnimepEngSw01#12]
São requisitos não ligados a funcionalidades do sistema. Ou seja, banco de dados, IDE, Maven, Casos de testes, Angular, Etc.

**Comment by gabs-rocha** [comment]
já separei os topicos, agr vou buscar a definição deles e o vinculo com o sistema

**Comment by gabs-rocha** [comment]
já fiz o texto, preciso apenas terminar de formatar corretamente!

**Comment by gabs-rocha** [comment]
Texto finalizado! Já está na pag. principal da Wiki

**Comment by HugoPeressin** [comment]
Revisado.
