### ISSUE TITLE
Passo a Passo para configuração do Eclipse para criação do projeto

### ISSUE THREAD

**Issue by gabs-rocha** [TatiTheFreaK/UnimepEngSw01#5]

**Comment by gabs-rocha** [comment]
Já fiz os passos da configuração e mandei para o @csenna subir na Wiki

**Comment by csenna** [comment]
Subindo fotos, realizando criação da WiKi

**Comment by gabs-rocha** [comment]
Processos
Criação do projeto - OK
Configuração do JDK - OK
Configuração do Servidor TomCat - OK

**Comment by csenna** [comment]
Processos
Criação do projeto - OK
Configuração do JDK - OK
Configuração do Servidor TomCat - OK
Configuração do Eclipse - Em andamento

**Comment by gabs-rocha** [comment]
@csenna precisa fazer isso para poder enviar o link para o professor!

**Comment by csenna** [comment]
Verificando

**Comment by csenna** [comment]
Feito Tutorial de Configuração do Eclipse e adicionado na home
